/**
 * Canonical list of Material Symbols used in the app (static + category-icons heuristics).
 * Keep sorted — required by Google Fonts subset API and for stable diffs.
 * Run `npm run icons:sync` after adding new icon names.
 */
export const MATERIAL_SYMBOL_ICONS = [
  "add",
  "add_business",
  "admin_panel_settings",
  "apps",
  "arrow_back",
  "arrow_forward",
  "bolt",
  "cached",
  "calendar_month",
  "check_circle",
  "checkroom",
  "chevron_left",
  "chevron_right",
  "cleaning_services",
  "close",
  "code",
  "dashboard",
  "delete",
  "directions_bike",
  "directions_car",
  "domain",
  "donut_small",
  "eco",
  "edit",
  "edit_note",
  "error",
  "event",
  "expand_more",
  "favorite",
  "filter_alt",
  "forest",
  "group",
  "group_off",
  "groups",
  "history",
  "home",
  "inbox",
  "info",
  "insights",
  "inventory_2",
  "leaderboard",
  "list",
  "list_alt",
  "logout",
  "mark_email_unread",
  "menu",
  "palette",
  "person",
  "person_add",
  "photo_camera",
  "progress_activity",
  "public",
  "recycling",
  "restaurant",
  "save",
  "school",
  "search",
  "settings",
  "share",
  "shopping_cart",
  "speed",
  "support",
  "trending_up",
  "tune",
  "tv",
  "visibility",
  "volunteer_activism",
  "warning",
  "water_drop",
] as const;

export type MaterialSymbolIcon = (typeof MATERIAL_SYMBOL_ICONS)[number];

/** Sorted copy for Google Fonts `icon_names` query param. */
export function materialSymbolIconsQueryParam(): string {
  return [...MATERIAL_SYMBOL_ICONS].sort((a, b) => a.localeCompare(b)).join(",");
}
